<a href="https://colab.research.google.com/github/fernando-123445/inteligenciaArtificial/blob/main/Actividad_de_Introducci%C3%B3n_a_Python_y_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NOMBRE: CARLOS FERNANDO ANCHUNDIA PARRAGA
#Fecha: 11/07/2024

In [1]:
# Importa numpy como np y muestra la versión

import numpy as np
print(np.__version__)

1.25.2


In [2]:
# Crear un arreglo 1D de números del 0 al 9

array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# Crear un vector aleatorio de tamaño 10 y reemplazar el valor máximo por 0
vector = np.random.rand(10)
print(vector)

print("\nValor maximo cambiado a cero")
maximo = np.argmax(vector)
vector[maximo] = 0
print(vector)

[0.97359795 0.97272183 0.96075969 0.42719847 0.03185746 0.7184514
 0.4315187  0.63073868 0.26077209 0.96355278]

Valor maximo cambiado a cero
[0.         0.97272183 0.96075969 0.42719847 0.03185746 0.7184514
 0.4315187  0.63073868 0.26077209 0.96355278]


In [4]:
# Imprimir el número 8 del siguiente arreglo:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, 2])

8


In [5]:
# Imprimir los números [3, 4, 5] del siguiente arreglo:
arr = np.array([1,2,3,4,5,6,7])
print(arr[2:5])

[3 4 5]


In [6]:
# Imprimir los últimos 4 números del siguiente arreglo:
arr = np.array([1,2,3,4,5,6,7])
print(arr[-4:])

[4 5 6 7]


In [7]:
# Crear un arreglo numpy de 3×3 con todos valores True
array = np.full((3, 3), True, dtype=bool)
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [8]:
# Extraer todos los números impares de arr
odd_numbers = arr[arr % 2 != 0]
print(odd_numbers)

[1 3 5 7]


In [9]:
# Crear un vector con valores que van de 10 a 49 (★☆☆)
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
# Revertir un vector (el primer elemento se convierte en el último)
vector = np.array([1, 2, 3, 4, 5])
vector_invertido = vector[::-1]
print(vector_invertido)

[5 4 3 2 1]


In [11]:
# Crear una matriz 10x10 con valores enteros aleatorios y encontrar el valor mínimo y máximo
matriz = np.random.randint(0, 51, size=(10, 10))

valor_minimo = np.min(matriz)
valor_maximo = np.max(matriz)

print("Matriz:")
print(matriz)
print("\nValor mínimo:", valor_minimo)
print("Valor máximo:", valor_maximo)

Matriz:
[[ 3 22 11 45 45 21 50 41 16  8]
 [14 44  2  2 29 19 31 33 47 34]
 [44  2  5 12 44 25 35 24 22 36]
 [11 18 16  1 34 43 11 39  1 39]
 [ 4 38 36  5 24  0 24 40 11  8]
 [ 5 14  4 18 14 35 22 47 15 25]
 [23 26 10 37 23 10  2 41 11 46]
 [41 20 22  7 44 35  0 31 10 44]
 [14 44 41  0 25 45  4 39 21 25]
 [42  5 24 21 13  1 24  6 45 42]]

Valor mínimo: 0
Valor máximo: 50


In [12]:
# Crear una matriz 3x3x3 con valores aleatorios
array_3d = np.random.random((3, 3, 3))
print(array_3d)

[[[0.14970208 0.36988907 0.37718975]
  [0.38944194 0.66142529 0.03092109]
  [0.97705056 0.07594679 0.74739426]]

 [[0.54751765 0.34665912 0.50419294]
  [0.24027251 0.79115537 0.90325504]
  [0.04317413 0.94926642 0.48452216]]

 [[0.06304042 0.20998299 0.31070922]
  [0.13367349 0.73341579 0.69824794]
  [0.8101582  0.40306843 0.62242492]]]


In [13]:
# Reemplazar todos los números impares en arr con -1
arr[arr % 2 != 0] = -1
print(arr)

[-1  2 -1  4 -1  6 -1]


In [14]:
# Crear un arreglo de tipo float
arr_float = np.array([1.5, 2.3, 3.1, 4.7, 5.5], dtype=float)

print(arr_float)
print(arr_float.dtype)

[1.5 2.3 3.1 4.7 5.5]
float64


In [15]:
# Convertir un arreglo 1D a un arreglo 2D con 2 filas
arr_1d = np.array([1, 2, 3, 4, 5, 6])

arr_2d = arr_1d.reshape(2, -1)

print("Array 1D:")
print(arr_1d)
print("\nArray 2D con 2 filas:")
print(arr_2d)

Array 1D:
[1 2 3 4 5 6]

Array 2D con 2 filas:
[[1 2 3]
 [4 5 6]]


In [16]:
# Cómo encontrar valores comunes entre dos arreglos?
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

valores_comunes = np.intersect1d(Z1, Z2)

print("Z1:", Z1)
print("Z2:", Z2)
print("Valores comunes:", valores_comunes)

Z1: [2 9 5 3 0 1 3 1 1 6]
Z2: [4 8 0 3 6 6 4 1 3 9]
Valores comunes: [0 1 3 6 9]


In [17]:
# Considerar dos arreglos aleatorios A y B, verificar si son iguales

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

comparacion = np.array_equal(A, B)

print("A:", A)
print("B:", B)
print("\n¿Son iguales?:", comparacion)

A: [0 1 0 0 0]
B: [1 1 0 0 0]

¿Son iguales?: False


In [18]:
# Apilar los arreglos a y b verticalmente
vertical_A = np.vstack((A))
vertical_B = np.vstack((B))

apilado_v = np.array([[vertical_A],[vertical_B]])
print(apilado_v)

[[[[0]
   [1]
   [0]
   [0]
   [0]]]


 [[[1]
   [1]
   [0]
   [0]
   [0]]]]


In [19]:
# Apilar los arreglos a y b horizontalmente
horizontal_A = np.hstack((A))
horizontal_B = np.hstack((B))

apilado_h = np.array([[horizontal_A],[horizontal_B]])
print(apilado_h)

[[[0 1 0 0 0]]

 [[1 1 0 0 0]]]


In [20]:
# Obtener todos los elementos entre 5 y 10 del arreglo tmp
tmp = np.arange(15)
resultado = tmp[(tmp >= 5) & (tmp <= 10)]

print(tmp)
print("\nElementos entre 5 y 10:", resultado)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Elementos entre 5 y 10: [ 5  6  7  8  9 10]


In [21]:
# Cómo hacer una función en Python que maneje escalares para trabajar en arreglos de NumPy?
# Pista
# Resultado deseado:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

# Vectorizar la función maxx
pair_max = np.vectorize(maxx)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

resultado = pair_max(a, b)

print("Array a:", a)
print("Array b:", b)
print("\nResultado:", resultado)

Array a: [5 7 9 8 6 4 5]
Array b: [6 3 4 8 9 7 1]

Resultado: [6 7 9 8 9 7 5]


In [22]:
# Intercambiar las columnas 1 y 2 en el arreglo arr.
# Pista
# Resultado deseado:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]

arr = np.arange(9).reshape(3,3)
print(arr)

# Intercambiar columnas 1 y 2
arr[:, [1, 2]] = arr[:, [2, 1]]

print("\nColumna 1 y 2 intercambiadas:")
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

Columna 1 y 2 intercambiadas:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [23]:
# Crear un arreglo 2D de forma 5x3 que contenga números decimales aleatorios entre 5 y 10.
# Pista
# El resultado deseado debería ser como el siguiente:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]


array_2d = np.random.uniform(5, 10, size=(5, 3))

print(array_2d)

[[6.22416149 7.74446064 7.08192921]
 [9.59245852 7.73383255 5.92589294]
 [8.10443749 5.84597267 9.35538842]
 [9.49855024 6.73183794 9.37496922]
 [8.5037309  6.95198615 9.68206223]]
