<a href="https://colab.research.google.com/github/fernando-123445/inteligenciaArtificial/blob/main/LUNEAS1JULIO2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#

In [8]:
import numpy as np
a=np.array([11,22,33])
print(a.shape)
print(type(a))
print(a)
print(a[1])

print(a[:2])

print(a[1:])

a=np.array([11, 22, 33])
print("Array original:", a)
a[1] = 888

print("Array actualizado:", a)

(3,)
<class 'numpy.ndarray'>
[11 22 33]
22
[11 22]
[22 33]
Array original: [11 22 33]
Array actualizado: [ 11 888  33]


#Arreglo en dos dimenciones

In [28]:
from re import sub

import numpy as np

b=np.array([[1,2,3],[11,22,33], [111,222,333]])
print(b.shape)
print(type(b))
print(b)

print(b[1,1])

submatriz = b[1:3, 1:3].copy()
print(submatriz.shape)
print("antes")
print(submatriz)

submatriz[1]=88
print("despues")
print(submatriz)
print(b)

(3, 3)
<class 'numpy.ndarray'>
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
22
(2, 2)
antes
[[ 22  33]
 [222 333]]
despues
[[22 33]
 [88 88]]
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]


In [21]:
c=np.zeros((4,4))
print(c)
print(c.shape)

d=np.full((4,4),9)
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [23]:
e=np.eye(3,3)
print(e)
f=np.ones((4,5))
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
g=np.random.random((5,5))
print(g)

[[0.96462934 0.18038634 0.497357   0.50650422 0.77797915]
 [0.50524479 0.16451948 0.78208051 0.87338644 0.68897571]
 [0.72902723 0.97708853 0.2645004  0.93097331 0.26496315]
 [0.32213699 0.8659651  0.26002375 0.78910927 0.99429025]
 [0.99936159 0.21074046 0.15737327 0.55791515 0.13288792]]


In [39]:
tmpl=np.random.randint(1, 20, size=(4,4))
print(tmpl)

rows=np.array([0,1,2,0])
cols=np.arange(4)
print(rows)
print(cols)

rows=np.array([0,1,2,0])
cols=np.arange(4)
print(rows)
print(cols)
print(rows.shape)
print(cols.shape)

tmpl[rows,cols]=100
print(tmpl)


[[ 8  7  3  4]
 [ 3  4 16 13]
 [13  4 13 12]
 [11 11  7  9]]
[0 1 2 0]
[0 1 2 3]
[0 1 2 0]
[0 1 2 3]
(4,)
(4,)
[[100   7   3 100]
 [  3 100  16  13]
 [ 13   4 100  12]
 [ 11  11   7   9]]


In [51]:
tmpl=np.random.randint(20, 50, size=(6,6))
print(tmpl)

filter=[tmpl>45]
print(filter)

filter=(tmpl>45)
print(filter)
print(tmpl[filter])

[[49 26 21 39 22 28]
 [26 26 48 35 48 32]
 [42 28 21 29 31 41]
 [44 46 49 29 29 34]
 [33 35 46 27 37 48]
 [39 45 37 20 20 25]]
[array([[ True, False, False, False, False, False],
       [False, False,  True, False,  True, False],
       [False, False, False, False, False, False],
       [False,  True,  True, False, False, False],
       [False, False,  True, False, False,  True],
       [False, False, False, False, False, False]])]
[[ True False False False False False]
 [False False  True False  True False]
 [False False False False False False]
 [False  True  True False False False]
 [False False  True False False  True]
 [False False False False False False]]
[49 48 48 46 49 46 48]


In [57]:
tmpl=np.random.randint(1, 100, size=(10,10))
print(tmpl)

filter=[tmpl % 2 == 0]
print(filter)

filter=(tmpl % 2 == 0)
print(filter)
print(tmpl[filter])

[[ 1 62  9 48 84 37 29 11 86 50]
 [ 2 22 70 48 40 92 21 84 97 59]
 [15 76 96  6 37 96 97 68 31 16]
 [71 78 45 52 13 17 20  7 19  1]
 [71 69 65 89 43 29  2 62 64 63]
 [58 12 70  4 32 96 50 55 20 29]
 [87 61 84 33 52 76 72 96 48 35]
 [ 3 33 73 82 90 44 71 65 10 23]
 [85 27 13 33 56 87 97 33 41  9]
 [37 25 50 48 63 27 26 82 64  3]]
[array([[False,  True, False,  True,  True, False, False, False,  True,
         True],
       [ True,  True,  True,  True,  True,  True, False,  True, False,
        False],
       [False,  True,  True,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False, False,  True, False, False,
        False],
       [False, False, False, False, False, False,  True,  True,  True,
        False],
       [ True,  True,  True,  True,  True,  True,  True, False,  True,
        False],
       [False, False,  True, False,  True,  True,  True,  True,  True,
        False],
       [False, False, False,  True,  True,  True, False, Fa

In [59]:
tmp3=np.array([1,2,3,4,5],dtype=np.float64)
print(tmp3.dtype)

float64


In [65]:
j = np.array([[1, 2], [11, 22]])
k = np.array([[22, 33], [44, 55]])


print("Array j:")
print(j)
print("\nArray k:")
print(k)


suma = j + k
print("\nSuma de j y k:")
print(suma)


resta = j - k
print("\nResta de j y k:")
print(resta)

multiplicacion = j * k
print("\nMultiplicación de j y k:")
print(multiplicacion)

division = j / k
print("\nDivisión de j y k:")
print(division)

raiz = np.sqrt(j)
print("\nRaíz cuadrada de j:")
print(raiz)

raiz = np.sqrt(k)
print("\nRaíz cuadrada de k:")
print(raiz)

Array j:
[[ 1  2]
 [11 22]]

Array k:
[[22 33]
 [44 55]]

Suma de j y k:
[[23 35]
 [55 77]]

Resta de j y k:
[[-21 -31]
 [-33 -33]]

Multiplicación de j y k:
[[  22   66]
 [ 484 1210]]

División de j y k:
[[0.04545455 0.06060606]
 [0.25       0.4       ]]

Raíz cuadrada de j:
[[1.         1.41421356]
 [3.31662479 4.69041576]]

Raíz cuadrada de k:
[[4.69041576 5.74456265]
 [6.63324958 7.41619849]]


In [69]:

tmpl = np.random.randint(1, 10, size=(2, 5))
print(tmpl)

promedio = np.mean(tmpl)

print("Promedio:")
print(promedio)




[[3 3 4 9 9]
 [1 9 3 6 6]]
Promedio:
5.3


In [71]:
print(tmpl.mean(axis=1))
print(tmpl.mean(axis=0))

[5.6 5. ]
[2.  6.  3.5 7.5 7.5]
